### PR TITLE
Autocomplete commands

### PR DESCRIPTION
**Pull request by namvd2709**

### CODE REVIEW

**Review by szalata — APPROVED** [review]
Nicely done. 👍 I think it would be nice to extend this feature to autocomplete persons names too

**Review by szalata — CHANGES_REQUESTED** [review]
I have just spotted that the pr hasnt been checked by travis. As we are required to use travis, I think it would be best to check it before merging.

**Comment by namvd2709** [comment]
I am not sure why travis is no longer auto run on PRs.

**Comment by namvd2709** [comment]
However, it seems to have been checked by Travis, just not reflected here:
https://travis-ci.org/CS2103AUG2017-T12-B1/main/builds/288639239

**Review by szalata — APPROVED** [review]

**Pull request merged**
